// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "api_key": string;
      "api_url": string;
      "model": string;
      "models": string;
      "active_model_id": string;
      "context_limit": string;
    };
  }
}
